### ISSUE TITLE
Some contact cards not visible even when data exists

### ISSUE THREAD

**Issue by thedivtagguy** [Vonter/blr-city-officials#53]
For example: 
![image](https://github.com/user-attachments/assets/8a694a87-88c4-4d95-96ad-6075d2bc31fc)

Whereas the data exists in the sheet: 
![image](https://github.com/user-attachments/assets/fec5ef9a-1482-4d29-992a-af67f09b6875)

Happens with almost all cards in the BWSSB Service Station category.

**Comment by Vonter** [comment]
Thanks for reporting and fixing this bug @thedivtagguy!
