### ISSUE TITLE
Link to exact row in Google Sheet corresponding to specific officer

### ISSUE THREAD

**Issue by Vonter** [Vonter/blr-city-officials#55]

**Comment by thedivtagguy** [comment]
I was _just_ working this one out. We can programmatically open a specific cell for commenting in Google Sheets. It allows deep-linking to specific cells based on the cell ID (unfortunately, contents are not searchable without authentication). So for instance: 

https://docs.google.com/spreadsheets/d/1lsXt4nXsz9k52bW79KxSLRK3Lg30z8U9AcuPNUHUVNY/edit?gid=1265603145#gid=1265603145&range=D399

Links to that specific officer. 

One easy way to do this would be to maintain a mapping of content to its current position that gets updated whenever the sheet changes, which can be as simple as adding a cell ID to the `officials.json` and constructing the URL based on that.

**Comment by Vonter** [comment]
Was about to implement it myself, but this implentation works even better. Thanks @thedivtagguy
